#!/bin/sh

red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
blue='\033[0;34m'
no_color='\033[0m'

echo -e ""
echo -e "${red}ε=ε=ε=┌( >_<)┘ ❗The compiled files for this project are not versioned, so an npm run prod may be necessary. ❗ε=ε=ε=┌( >_<)┘${no_color}"
