name: Create release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-zip-upload:
    runs-on: ubuntu-latest
    env:
      RELEASE_NAME: 'Simple'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

        # Compile the theme
      - name: Compile CSS and Javascript
        run: |
          npm ci
          npm run prod && npm run build:react-blocks

      # Zip the theme into a clean release
      - name: Zip release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: '${{ env.RELEASE_NAME }}.zip'
          path: 'LICENSE readme.txt screenshot.jpg functions.php style.css theme.json styles/ templates/*.html parts/*.html patterns/*.php blocks/react/build lang/ inc/ build/ acf-json/'

      # Publish the release
      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          artifacts: '${{ env.RELEASE_NAME }}.zip'
          generateReleaseNotes: true
